### ISSUE TITLE
Create a model for Prototype Projects Viewer window

### ISSUE THREAD

**Issue by Guitarheroua** [Guitarheroua/protomorph-bg#21]
Create a model for Prototype Projects Viewer window, for view, where all prototype projects will be displayed. 
* No modification of recent projects list from model for now
* Use standard DisplayRole and DecorationRole for showinf item name and icon.
* Add tests for model

**Comment by alexchmykhalo** [comment]
See recomendations for implementing Prototype Projects Viewer window UI: ![PPVW-UI-recomendations](https://user-images.githubusercontent.com/6122913/60117295-7cfcdd80-9782-11e9-8e9f-c38b5604025b.png)

**Comment by alexchmykhalo** [comment]
**Architectural Note:** 
https://yuml.me/edit/99f85f47
