### ISSUE TITLE
Create Prototype Components Navigator window

### ISSUE THREAD

**Issue by Guitarheroua** [Guitarheroua/protomorph-bg#23]
Create Prototype Components Navigator window (see Prototype Components Navigator UI recommendations in comments). No design available, so now the window should be only functionally correct.

Notes:

- DO NOT style widgets, proper colors and styles for UI will be set in the separate ticket.
- Follow recommendations for UI implementation (see comments)
- Ensure that you created a separate class and that class has interface described in architectural note (see comments).
- Button for loading component should only be enabled if there is only one selected component
- Button for removing component should only be enabled if there are one or many selected components

**Comment by alexchmykhalo** [comment]
See recommendations for Prototype Projects Viewer window UI implementation:
![PCNV-UI-recommendations](https://user-images.githubusercontent.com/6122913/60336499-2cb39480-99a9-11e9-96b7-bff9abbdaffc.png)

**Comment by alexchmykhalo** [comment]
**Architectural note:**
https://yuml.me/edit/87268b13
Signals should be emitted on corresponding button clicks. Double click on item in the view should trigger component opening.

**Comment by okotik** [comment]
@alexchmykhalo @Guitarheroua Що саме означає коментар на картинці "copy this gray rect with text as an icon for delegate"? Що за делегати повинні бути?

**Comment by Guitarheroua** [comment]
> @alexchmykhalo @Guitarheroua Що саме означає коментар на картинці "copy this gray rect with text as an icon for delegate"? Що за делегати повинні бути?

@okotik Please read this part of the documentation, https://doc.qt.io/qt-5/model-view-programming.html where delegates are described. Delegate is a UI representation of item from the model in view.

P.S. Better to have a conversation in English here, as we work or may work not only with people from Ukraine but from other countries.
