### ISSUE TITLE
Create Prototype Projects Viewer

### ISSUE THREAD

**Issue by Guitarheroua** [Guitarheroua/protomorph-bg#6]
Here all prototypes projects should be displayed. From here it is
possible to open/create or delete a project. After the project opened/created we will go to Prototype Components Navigator.

This is a complex task and will be separated into smaller in the future.

**Notes:**
 * DO NOT style widgets, proper colors and styles for UI will be set in the separate ticket.
 * Follow recommendations for UI implementation (see comments)
 * Ensure that you created a separate class and that class has interface described in architectural note (see comments).
* Button for loading component should only be enabled if there is only one selected component
* Button for removing component should only be enabled if there are one or many selected components

**Comment by alexchmykhalo** [comment]
See recommendations for Prototype Projects Viewer window UI implementation: 
![PPVW-UI-recomendations](https://user-images.githubusercontent.com/6122913/60117609-057b7e00-9783-11e9-86ea-da705a834924.png)

**Comment by alexchmykhalo** [comment]
**Architectural note:** 
Class interface: https://yuml.me/edit/27afdb38
Signals should be emitted on corresponding button clicks. Double click on item in the view should trigger project opening.
